### ISSUE TITLE
bad parameters to bluetooth.open() on imp006

### ISSUE THREAD

**Issue by Moneil97** [electricimp/BTLEBlinkUp#4]
I get this error on imp006 when trying to use this library:

```
2023-09-01T15:23:24.581 +00:00	[Device]	ERROR: BLE failed to initialize (error: bad parameters to bluetooth.open() (line 673))
2023-09-01T15:23:24.581 +00:00	[Device]	ERROR:   in _init device_code:675
2023-09-01T15:23:24.581 +00:00	[Device]	ERROR:   from constructor device_code:236
2023-09-01T15:23:24.585 +00:00	[Device]	ERROR:   from main device_code:847
```

due to this code:
https://github.com/electricimp/BTLEBlinkUp/blob/abcd65f238d050a36c477aabd614ac57e35cdced/btleblinkup.device.lib.nut#L549

`hardware.bluetooth.open(firmware)` should be `hardware.bluetooth.open()` on imp006

"imp006
The imp006’s Cypress CYW43455 chip is connected on a dedicated UART which is not exposed via Squirrel and consequently not configurable by your application. In addition, the imp006’s modem firmware is supplied and loaded by impOS. The MAC address cannot be changed. Therefore hardware.bluetooth.open() on the imp006 takes no arguments, as you can see from the example code, below. If you provide arguments, an exception will be thrown." - https://developer.electricimp.com/api/hardware/bluetooth/open

**Comment by smittytone** [comment]
There's an updated version of the library that makes this and other changes. See the `develop` branch. I cannot say when the updated version will be formally be released to be accessible via `#require` so I would recommend manually copying the library code from `develop` to the head of  your own device code (or including it pre-upload with Builder).
